<?php

define('PATH_BASE',    __DIR__.DIRECTORY_SEPARATOR);
define('PATH_CORE',    PATH_BASE.'bff'.DIRECTORY_SEPARATOR);
define('PATH_PUBLIC',  PATH_BASE.'public_html'.DIRECTORY_SEPARATOR);
define('PATH_MODULES', PATH_BASE.'modules'.DIRECTORY_SEPARATOR);